name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image for Backend
        run: |
          cd back-end
          docker build -t localhost:5000/backend-service .
        
      - name: Build Docker Image for Frontend
        run: |
          cd front-end
          docker build -t localhost:5000/frontend-service .

      - name: Log in to Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login localhost:5000 -u ml23-1 --password-stdin

      - name: Push Docker Image for Backend
        run: |
          docker push localhost:5000/backend-service

      - name: Push Docker Image for Frontend
        run: |
          docker push localhost:5000/frontend-service

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes with Persistent Volume
        run: |
          kubectl apply -f k8s/volume.yaml
          kubectl apply -f k8s/flask-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
